services:
  vscode-server:
    build: .
    image: ghcr.io/robertocjunior/vscode-server:main
    container_name: vscode-server
    environment:
      - GIT_USER_NAME=roberto
      - GIT_USER_EMAIL=robertocasalijunior@gmail.com
      - GITHUB_REPO= # Cole o link do repositório aqui (ex: https://github.com/user/repo.git)
      - TUNNEL_NAME=my-vscode-server # Nome opcional para o seu túnel
    volumes:
      - ./workdir:/opt/dev
    restart: unless-stopped
    # Privileged pode ser necessário para algumas operações de root dentro do container
    privileged: false 
