services:
  web-terminal:
    build: .
    image: ghcr.io/robertocjunior/web-dev-server:main
    container_name: web-terminal
    ports:
      - "7681:7681"
    environment:
      - GIT_USER_NAME=roberto
      - GIT_USER_EMAIL=robertocasalijunior@gmail.com
      - GITHUB_REPO=
    volumes:
      - ./workdir:/opt/dev
      - ./workdir/.config:/root/.config
      - ./workdir/.local:/root/.local
    restart: unless-stopped
    privileged: false
